[2024-10-09 10:41:29,883] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-09 10:41:29,895] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-09 10:41:29,895] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 10:41:29,896] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-10-09 10:41:29,896] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 10:41:29,928] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BTC> on 2024-09-30 00:00:00+00:00
[2024-10-09 10:41:29,938] {standard_task_runner.py:52} INFO - Started process 68735 to run task
[2024-10-09 10:41:29,943] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_crypto_dag', 'BTC', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/get_crypto.py', '--cfg-path', '/tmp/tmpezmt6ccx', '--error-file', '/tmp/tmpsc24ga01']
[2024-10-09 10:41:29,944] {standard_task_runner.py:80} INFO - Job 447: Subtask BTC
[2024-10-09 10:41:31,588] {task_command.py:370} INFO - Running <TaskInstance: get_crypto_dag.BTC scheduled__2024-09-30T00:00:00+00:00 [running]> on host ken
[2024-10-09 10:41:32,204] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_crypto_dag
AIRFLOW_CTX_TASK_ID=BTC
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T00:00:00+00:00
[2024-10-09 10:41:32,802] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/airflow/dags/get_crypto.py", line 21, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/yfinance/base.py", line 80, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 256, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 381, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/kennedy/KR/Programação/00.Estudos/DataEng/Alura/airflow-executores/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-10-09 10:41:32,872] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_crypto_dag, task_id=BTC, execution_date=20240930T000000, start_date=20241009T134129, end_date=20241009T134132
[2024-10-09 10:41:33,553] {standard_task_runner.py:92} ERROR - Failed to execute job 447 for task BTC (index 0 is out of bounds for axis 0 with size 0; 68735)
[2024-10-09 10:41:33,610] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-09 10:41:33,909] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
